sonar.projectKey=portal-fe
sonar.organization=dev-sec-ops-sharing
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**
sonar.coverage.exclusions=src/app/**,src/**
sonar.qualitygate.wait=true
