name: Deploy Production

on:
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  deploy-production:
    name: 🚀 Deploy Production
    uses: dev-sec-ops-sharing/devsecops-infra/.github/workflows/build-deploy.yml@main
    with:
      service-name: portal-fe
      environment: 'production'
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      API_URL: ${{ secrets.API_URL }}
